### ISSUE TITLE
[Feature request] Define to use variables without NPMRC_ prefix in configuration

### ISSUE THREAD

**Issue by szulcus** [dennzimm/npmrc-replace-env#12]
First of all, thanks for this awesome package! ❤️

We have already defined global env variable and I want to stay with previous name. It is possible?

**Comment by dennzimm** [comment]
> First of all, thanks for this awesome package! ❤️
> 
> 
> 
> We have already defined global env variable and I want to stay with previous name. It is possible?

Hello szulcuz! Thanks for the kind words and glad you're using / want to use this package 🙂 That's a good point, I'll try to implement flags today or tomorrow to control this behavior (e.g. something like `--prefix CustomPrefix`, or `--without-prefix` so you can use your own keys) and will let you know then 😊

**Comment by dennzimm** [comment]
Hi @szulcus :) 

With the latest update, you now have the ability to define environment variables without the NPMRC_ prefix.
To learn how to utilize the new command-line options for custom environment variable prefix and disabling prefix usage, please refer to the [dedicated section in the README](https://github.com/dennzimm/npmrc-replace-env?tab=readme-ov-file#command-line-options) documentation.

Thank you for helping to improve the package! If you have any further questions or suggestions, feel free to reach out. Happy coding! 🚀
